### ISSUE TITLE
"npm install" fails due to "sparkling-sky" package

### ISSUE THREAD

**Issue by ParinVachhani** [ParinVachhani/FoodToGo#3]

**Comment by ParinVachhani** [comment]
Fails because sparkling-sky does not exist npm package registry:
http 404 https://registry.npmjs.org/sparkling-sky

**Comment by ParinVachhani** [comment]
First we had to publish our project to npm using "npm publish"
https://docs.npmjs.com/getting-started/publishing-npm-packages
Another helpful link for common npm issues:
https://github.com/npm/npm/wiki/Troubleshooting

**Comment by suhasdarsi** [comment]
To fix the path issue use this
sudo ln -s /usr/bin/nodejs /usr/bin/node

Link to the article
http://www.hostingadvice.com/how-to/install-nodejs-ubuntu-14-04/

**Comment by ParinVachhani** [comment]
Stackoverflow thread regarding similar issue:
http://stackoverflow.com/questions/26320901/cannot-install-nodejs-usr-bin-env-node-no-such-file-or-directory

Other links explaining this issue in context of Debian & it's derivatives:
https://github.com/nodejs/node-v0.x-archive/issues/3911
https://github.com/atom/atom/issues/2025
